#Script para instalar las dependencias

import os
os.system("sudo apt-get install clang")
os.system("sudo apt-get install screen")
os.system("sudo pip2 install bs4")
os.system("sudo pip2 install simplejson")
os.system("sudo pip2 install pycrypto")
os.system("sudo pip2 install cryptography")
os.system("sudo pip3 install bs4")
os.system("sudo pip3 install colorama")
os.system("sudo pip2 install prettytable")
os.system("sudo pip2 install colorama")
os.system("sudo pip2 install requests")
os.system("sudo pip2 install cfscrape")
os.system("sudo pip2 install prettytable")
os.system("sudo pip2 install click")
os.system("sudo pip3 install colorama")
os.system("sudo pip3 install proxybroker")
os.system("sudo pip3 install cfscrape")
os.system("clear")
